# Generated by Django 2.0.5 on 2019-01-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=20),
        ),
    ]
