# Generated by Django 2.0.5 on 2019-01-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weigth',
            new_name='weight',
        ),
    ]
